feat: QueryDsl 설정
dnd-side-project/dnd-11th-5-backend pull request #13
Opened 2024-07-24 05:05 UTC by yueunfive

# 요약
QueryDsl 기본 설정 추가

# 작업 내용
- [ ] 의존성 추가 및 Config 파일 생성

close #12

2024-07-25 07:29 UTC, punchdrunkard approved these changes
![image](https://github.com/user-attachments/assets/efa0fc10-9921-405e-8a5f-129e774b0c62)

`querydsl` 에 의해 생성된 파일이 `git` 에 추가되고 있습니다!
`.gitIgnore` 에 해당 디렉토리 추가해주세요.

2024-07-25 07:33 UTC, punchdrunkard requested changes

2024-07-25 07:33 UTC, punchdrunkard commented on build.gradle
> +def generated = 'src/main/generated'
해당 폴더 `.gitIgnore` 에 추가해주세요!

+ 의견
queryDsl으로 생성한 쿼리의 경우 `test` 에서도 사용하게 될 텐데, `main` 폴더에 `generated` 폴더 아래 `Qtype` 을 생성하는 것 보다 `build` 와 같은 폴더에 생성하는게 어떨까요?

2024-07-25 07:34 UTC, punchdrunkard requested changes
안녕하세요, 유은님!
첫 코드리뷰네요. 앞으로 잘 부탁드리겠습니다~

궁금한 점과 제안 사항 리뷰로 남겨드렸습니다.
구현하시느라 수고 많으셨습니다!

2024-07-25 07:45 UTC, punchdrunkard approved these changes

2024-07-27 00:32 UTC, yueunfive commented on build.gradle
> +def generated = 'src/main/generated'
가져온 코드이긴 한데, [참고 자료](https://velog.io/@may_yun/1-QueryDSL-%ED%99%98%EA%B2%BD-%EC%84%A4%EC%A0%95)에서는 "IDE와 queryDSL의 중복을 막기위해 위치를 꺼내 놓는 추가 설정"이라고 하네요!

2024-07-27 00:33 UTC, merged